[package]
name = "openai-cli"
version = "0.1.0"
edition = "2021"
author = "LevitatingBusinessMan"
description = "CLI for the OpenAI API"
repository = "https://github.com/LevitatingBusinessMan/gpt-cli"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.8", features = ["derive"] }
openai-rust = "0.1.0"
reedline = "0.17.0"
tokio = { features = ["macros", "rt-multi-thread"], version = "1.26.0" }
